apiVersion: v1
kind: Template
metadata:
  labels:
    provider: fabric8
  name: fabric8-oauthclient-template
parameters:
- name: URL
objects:
- apiVersion: v1
  kind: OAuthClient
  metadata:
    name: fabric8-online-platform
  secret: fabric8
  redirectURIs:
  - "http://${URL}"
  - "https://${URL}"
  grantMethod: prompt
